apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: crud-db-secret
  namespace: local
spec:
  encryptedData:
    password: AgA7UyYP0x7FVi8+VD0x7dhkBRjD0mHo0982SRMQQYVYIU55sPlA+v1OdpQvKvwm0UeGNtFbhpVd8RpCwxRq2bCvGfRNIlKmp3fn8GVC8HsFSFlRIdxm1gNQlY0Q1Hx6hTvo6yfRnFuMc+IUEhpNWnM+P8sn0i3s/1icJu1ShbUKDA3cb3KhDpE9evKbstTFmN90zGNCIztmfplKMWdKfOVmll2DJ1e4+y/0yu0qBX5zEGyDPEwWK/nDJegR5QmkUgXCCfhQBIWUDjC8sNkFeSZSgm+Tgxfj+Qis43bGzY0RwKdpH2RuDNCA1IGYogTLEDDh29v0sKMyVOmu6gmIp9H+Yynmkk/wYnsZelovP/+8DBPyx+fAkOoXR0P+MfYg0hYqihzRItCht9zxblcTmjTQxBuwlzZQh871f49pKguikuFHeiwlHZfQDaBom8r9f4p66otQvnuzDSM2eHZIpcwoQkyAdo9HpD26dnEiQImXWqOaLgXRdQCwc26P63jHKRLUcn2kPV6bZOptl8HhgNoClzs0Okn8zeMkAp+ZrP5KjRfhmKLSqpZvUn8qWrUMRBwqnE7iKX9TneFHBbICeZfsyrHtJazBOLuf0TOzmk2CHiDbqmPj+nt+R5pTBtO4MktEh4MufF15QjIUKXdZdfwFvu8WeLRjEKOuPvx+ianu1u34lo92iArG0sBFP4w7iiba8zGGv/a0Ow==
    username: AgDCJdwA+C91Gl1Q7+lMjs0J+Kwik+sr2FKQSrjs3tefRNlKlt9iamQnSwiRpSGgu2oeIEVddv1tFFurgxEDtzJfJ3Qbuq9kZnjxeZe5GzOVY20VgWsK4rzrJbt81emp7XdAwLlO8Hxaz3TXsysvZTf8ZcaYQCvUzkHS+bQmWy46T2A19jmlrpFlB1r8kaCDUJKOV7deoN9haxN0qAiUPDB/xMcDVa4w8VyKI40qt7z3YgJEe/pJk/ZWLpiuuLYGumWGQrFp3GJyFfgG426lpHuHxRfnRmPUCMSl75Hqy4yFnENPWL3yreNH+aF1nhV4YFCli1GeyBwZCmBDuxxuejXEX+TR/DzpE8QFzrxfn11HXGHkXC/hyyTyoGLysVYLpK9b9nTSR/9d/h81tLSkMwij4GcpH5MAezHx6IFHXE1qG7gRUzuKgId79xo5IH1o0muwTVhCw4Tt+mjbxVap7+VMyWT3FmDpU+/Xqz9AaocbMOcgtSrg5rPmtM/vZSTiZqTdswIX/eKL119zNWY0vlYmPIrzc5uCKc0IgFK8XDGMerKAktDOYrS96O/+r6v+iveIg/MO+0cewFxNOISXndZkkn/Bz+zx3VKrMCBR9qGxrM3YLvZ1VtAgAgw1yOJiOyK/zBLCXyxiAVM81ZNpa4ZnQSlOcc9O17QkgonPVDLrrzMhLGx5bxsaBsoFWkayb29G7UCm
  template:
    metadata:
      creationTimestamp: null
      name: crud-db-secret
      namespace: local
    type: Opaque

