apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: crud-db-secret
  namespace: dev
spec:
  encryptedData:
    password: AgAq8RNdHtufiNewfKMFc7uBS+2oR1znxRCXtqFinIGA15H4wlLW/1J/wKrGxFN4zRmt0UBdQpcqQlW4SGq+W9VxCJ1sj0e+peBTNQhJ1eTilIDukjJkNN1DYoglNHFzXA3sddj7xQ/fKQGUrDjHOyPv3PbLgYMkUBPSiJz7BvUC0N0dWN8+PXPwn6Tf6VMrL81p1EYR2irl3MoQbhWTtmfV0snxDSUoIy6vJzNSDDhJwIMa07fvEJ+uB+uKY1iENzP3+hf2Bn/SIpsBqopQSQl7RxsTPpKUvCdc4YKP/jGG3HrGEQ925c+0aN0etbmY+PhS2w8gSuv8vmYWKcRi6np7Ki0uKpaKzgqkl2dtDH6UBc2vKw/6cFLBwZvvEd1xO+smiN/7LzD5mu5YAuFfZR+Jm+gGfX2Ko+Bpsr21tPykO3IZpwU+RJRs1YfCDsYoCfBxnjuJHnOBg0usQrMkhT8JNqUOxf4eB06OtF90Yb2zsz9GK3DVGhpxhoxZtx57zsKjfFSQrxaxPAzcYTL1ZpPuWiv+VadMXKP7sVyTSx2HhDuOLaWgFLL4cZvMSUwd87iDOhwwjaUHdGAeEEKfSs5MRIH6mAWJT1ToVVBrwq2ytT4M/NZaBRDG0BI7RxNjYHi+5dXy/Tf7xXadyk+E4MB7OvPL04ZtWR+O7pY3dehV+vtTTljFKFHGCnEG8jkVufl0KEnsb2KEDQ==
    username: AgBpEGdDbHYbubnMoIBkc9NVhkgRIekvKCPrz7IYqju/CIKiDruD92dj1K+HdIsCUNjebIl2Y+jnss+SCDaTXYaXdi4//0tv2GnipCqimHd0oz3Q17wmQd1Qe/q8laWOYpwCkkg1i7XQZoLfr79xyl68pYnTsCxJylVJfAbs56Vwczu2WIc9qwCHhKQnKXzTYyFRYPITV+Ftld6L61EhNpU6T+8lpW/7tUSjLU/1zASyKQdl0VqQr23z/GH1tohY2+YzSiE/ZAQ/O8fvl+BcJsbiD4QKoveiEyTGQAAEvURs09EQvHdaIv/4ZZE8cWUgmje/Xdp248CQeeIcgp1bkIho2+2Blnikxe4xnBLiEo+oWCm4tJjKQdlpYQgJYSoohnKP+zXY/y+JmJTXW5Gc6Tsnx2i3L9MQztes9yINz3BFzMYM5ClGY8Nt1Cb3jeFxVRAJZFG6nS2qsj72GvGk8o6tIAlb157oZfA2TIZ8rLsj3vrpLUtzrbmWj8NV4d1fRhsneRqGcsmLKhNbdeBOTsxctwJOOc8YoMr1j8Pmt0T1nU2kEDWo/ryPKi3AG+bOQ2Ny0LeDFB4M+ofylZpKElH43P9vQrKBtNFKDy6F/PPKS/M6kceeejTihYhIR2ympXUAQF27N2KLx6QqFBYZlbzY9OIU/diNgQ2NKhAypTXw2XZto29S0IgWtm99WSBM/ff/LG1w
  template:
    metadata:
      creationTimestamp: null
      name: crud-db-secret
      namespace: default
    type: Opaque

