apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: crud
          image: devops1600/crud-node
          command: ["./start.sh"]
          ports:
            - containerPort: 3000
          env:
            - name: TITLE
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: TITLE
            - name: HOSTDB
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: HOSTDB
            - name: PORTDB
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: PORTDB
            - name: USERDB
              valueFrom:
                secretKeyRef:
                  name: crud-db-secret
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crud-db-secret
                  key: password
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 25
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 50
            periodSeconds: 5