apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec: 
  project: default
  source:
    repoURL: https://github.com/1600-services/argocd-sandbox.git
    targetRevision: HEAD
    path: enviroments/staging/my-app2
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - prunePropagationPolicy=foreground
      - PruneLast=true
